- name: GitHub Readme YouTube Cards
  # You may pin to the exact commit or the version.
  # uses: DenverCoder1/github-readme-youtube-cards@781a89673301125a08e008dd2b85dc6c2d91a4c6
  uses: DenverCoder1/github-readme-youtube-cards@1.4.0
  with:
    # The channel ID to use for the feed
    channel_id: 
    # The language you want your cards description to use
    lang: # optional, default is en
    # The name of the comment tag to use for the cards
    comment_tag_name: # optional, default is YOUTUBE-CARDS
    # The maximum number of videos to display
    max_videos: # optional, default is 6
    # The base URL to use for the cards
    base_url: # optional, default is https://ytcards.demolab.com/
    # The YouTube API key to use for additional features such a the video duration
    youtube_api_key: # optional, default is 
    # The width of the SVG cards
    card_width: # optional, default is 250
    # The background color of the SVG cards
    background_color: # optional, default is #0d1117
    # The color of the title text
    title_color: # optional, default is #ffffff
    # The color of the stats text
    stats_color: # optional, default is #dedede
    # JSON theme for light mode (keys: background_color, title_color, stats_color).
    theme_context_light: # optional, default is {}
    # JSON theme for dark mode (keys: background_color, title_color, stats_color)
    theme_context_dark: # optional, default is {}
    # Whether to show the video duration. Requires `youtube_api_key` to be set.
    show_duration: # optional, default is false
    # The name of the committer
    author_name: # optional, default is GitHub Actions
    # The email address of the committer
    author_email: # optional, default is 41898282+github-actions[bot]@users.noreply.github.com
    # The commit message to use for the commit
    commit_message: # optional, default is docs(readme): Update YouTube cards
    # The path to the readme file
    readme_path: # optional, default is README.md
    # Whether to return the section markdown as output instead of writing to the file
    output_only: # optional, default is false
    # The type of output to be rendered by the action ('markdown' or 'html')
    output_type: # optional, default is markdown
